blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #to load the image
from django.conf import settings # for line 28 onwards

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('myapp.urls')),
    path('', include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

blog/myapp/urls.py
from django.urls import path
from . import views
from .views import (
    DestinationDetailView
)

app_name = 'myapp'

urlpatterns = [
    path('', views.home_page_logged_in, name = 'home page'),
    path('register', views.register, name = 'register'),
    path('sign-in', views.sign_in, name = 'sign-in'),
    path('login', views.login, name = 'login'),
    # path('logout', views.logout, name = 'logout'),
    path('log_out', views.log_out, name = 'logout'),
    path('feedback', views.display_feedback, name = 'display feedback'),
    path('create-feedback', views.create_feedback, name = 'create feedback'),
    path('check-delete', views.check_delete, name = 'check delete'),
    path('delete/<str:pk>', views.delete, name='delete'),
    path('individual-feedback/<str:pk>', views.individual_feedback, name='individual feedback'),
    path('destinations/<slug>/', DestinationDetailView.as_view(), name = 'destinations'),
    # path('test-destination', views.test_destinations, name = 'destinations')
  ]

blog/myapp/models.py
from django.db import models
from django.conf import settings #Use the auth_user model from Django
from django.contrib.auth.models import User
from django.shortcuts import reverse #New Line
from datetime import datetime


# CATEGORY_CHOICES = (
#     ('JP', 'Japan'),
#     ('AU', 'Australia'),
#     ('DK', 'Denmark')
# )


COUNTRY_CHOICES = (
    ('JP', 'Japan'),
    ('AU', 'Australia'),
    ('DK', 'Denmark')
)

LABEL_CHOICES = (
    ('F', 'Free'),
    ('P', 'Paid')
)


# Create your models here.

class Post(models.Model):
    author_id = models.ForeignKey(User, on_delete = models.CASCADE) 
    title = models.CharField(max_length = 100)
    body = models.CharField(max_length = 1000000)
    created_at = models.DateTimeField(default = datetime.now, blank=True)

#Destination
class Destination(models.Model):
    name = models.CharField(max_length=100)
    # category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    # label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    country = models.CharField(choices=COUNTRY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    price = models.FloatField(blank=True, null=True) #Some places are free
    discount_price = models.FloatField(blank=True, null=True)
    
  
    def __str__(self):
        return self.name

    #This code is complete
    def get_absolute_url(self):
        return reverse("myapp:destinations", kwargs={
            'slug': self.slug
        })

    #WORK ON THESE BELOW
    # def get_req_add_to_log(self):
    #     return reverse("core:add-to-cart", kwargs={
    #     'slug': self.slug
    #     })

    #WORK ON THESE BELOW
    # def get_req_remove_from_log(self):
    #     return reverse("core:remove-from-cart", kwargs={
    #         'slug': self.slug
    #     })




#Able to create Destination Object via admin

#DestinationLog - Relationship Between Trip and Destination
# class OrderItem(models.Model):
#     pass

#Multiple destination logs are stored in a trip
# class Trip(models.Model):
#     pass

blog/myapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm #built in creation form
from django.contrib.auth.models import User 
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body"] #WHY IS THIS NTO SHOWING ThE TEXT FIELDS?

blog/myapp/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone

from django.views.generic import ListView, DetailView, View
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import reverse

from .models import *
from .forms import *

# Create your views here.

# class HomeView(ListView):
#     model = Item
#     paginate_by = 10
#     template_name = "home.html"


def home_page_logged_in(request):
    return render(request, "base/home_page_logged_in.html")


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username'] #from the name = "username" store it in a variable on the left
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Already Used') #Check if email exists, if yes, return message
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Already Used ') 
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, email=email, password=password1, 
                 first_name=first_name, last_name=last_name) #Create user
                user.save();
                return redirect('/')
        else:
            messages.info(request, 'Password is not the same')
            return redirect('register')
    else:
        return render(request, "user_authentication/register.html")

# #BACK UP SIGN IN CODE
def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
    
        if user is not None:
            auth.login(request, user)

            return redirect('/') 

        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('/sign-in')
    else:
        return render(request, "user_authentication/sign-in.html")

#CORRECT ALREADY - 11-07-2023
#11-8 login not working/ always finding for registration/login
#Must be when I ran website project
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/') #CORRECT DONT CHANGE

        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('/login') #CORRECT DONT CHANGE

    else:
        return render(request, "user_authentication/login.html")

def log_out(request): 
    auth.logout(request)
    return redirect('/')


#Testing with default variable name [DO NOT DELETE]
# def logout(request): 
#     auth.logout(request)
#     return redirect('/')
    #For some reason always returns the Django Admin Page
    #Use log_out for now


def display_feedback(request):
    posts = Post.objects.all()
    return render(request,"posts/display_feedback.html", {'posts' : posts})

def individual_feedback(request,pk):
    posts = Post.objects.get(id=pk)
    return render(request,"posts/individual_feedback.html", {'individual_posts' : posts})
    #the values in {'individual_posts' : posts} doesn't have to be the same!!!
    #it is {{individual_posts}} THAT MUST BE QUERIED IN THE HTML FILE.
    
# @login_required(login_url = "/login")
# def create_feedback(request):
#     if request.method == 'POST':
#         create_post = CreatePost(request.POST)
#         if create_post.is_valid():
#             create_post = create_post.save(commit=False) #post is just a variable name
#             create_post.author_id =  request.user #access the user currently signed in
#             create_post.save()
#             return redirect('/feedback')
#     else:
#         create_post = CreatePost()
#     return render(request, "posts/create_feedback.html",  {"create_post" : create_post} )

@login_required(login_url = "/login")
def create_feedback(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            create_post = form.save(commit=False) #post is just a variable name
            create_post.author_id =  request.user #This is needed if you add the models.ForeignKey(User, on_delete = models.CASCADE) in models
            #essentially it takes the current logged in user and stores it as author_id
            create_post.save()
            return redirect('/feedback')
    else:
        form = PostForm()
    return render(request, "posts/create_feedback.html",  {"form" : form} )

def check_delete(request):
    # posts = Post.objects.all()
    # posts = Post.objects.all().values()[1]
    # posts = Post.objects.values_list('author_id','id','title')
    # return render(request, "base/check_delete.html",  {"posts" : posts} )
    return render(request, "base/check_delete.html")

def delete(request, pk):
    post_id = Post.objects.get(id=pk)
    print(post_id)
    post_id.delete()

    return redirect('/feedback')
#Simple Delete Function, Since we have implemented  {% if user == post.author_id %} in html file,
#it should work that only author can delete posts for now.

#This Code is Complete
class DestinationDetailView(DetailView):
    model = Destination
    template_name = "base/destination_catalogue.html"
 

blog/myapp/templates/base/check_delete.html
{% extends 'base/master.html' %}

{% block title %}
Check Delete
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    
    <!-- <h1>Using value list, value is: </h1> {{posts}} -->

    <h1>Sorry, you're not allowed to delete the post!!!</h1>
{% endblock %}

blog/myapp/templates/base/destination_catalogue.html
{% extends 'base/master.html' %}

{% block title %}
Travel Catalogue
{% endblock %}

{% block content %}
    <h1>Travel Catalogue</h1>
     
    <main class="mt-5 pt-4">
      <div class="card">
              
             
      <h2>{{ object.name }}</h2>
      <p>Country: {{ object.get_country_display }} | {{ object.get_label_display }} </p>

              <!-- We created a tuple for countries stored in models.py, label refers to Initials
              display refers to the stored values-->
              <!-- <p>Country: {{ object.country }} | {{ object.label }} </p> -->
      
  <!--BELOW BROKEN-->
          <div class="view overlay">
          <img src="{{ destination.image.url }}" class="card-img-top"> <!--Supposed to run image-->
            <!-- <img src="shinsaibashisuji_1.jpg" class="card-img-top">  <!Supposed to run image-->    
          </div>
  <!--END-->  

<!--Everything below WORKS-->         
            <!--Price-->
            <p class="lead">
              {% if object.discount_price %} <!--If object has a discount price-->
              <span class="mr-1">
                <del>${{ object.price }}</del> <!--Strike out orignal price-->
              </span>
              <span>${{ object.discount_price }}</span> <!--Display Discounted price-->
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>
  
            <!--Description-->
            <p class="lead font-weight-bold">Description</p>
            <p>{{ object.description }}</p>
        
        
          </div>  

        </div>
      </div>
    </main> 
{% endblock %}

blog/myapp/templates/base/home_page_logged_in.html
{% extends 'base/master.html' %}

{% block title %}
TravelAI Main Page
{% endblock %}

{# Page when is logged in #}

{% block content %}
<div class = "main">

    {% if user.is_authenticated%}
    <h1>Welcome to, Travel AI {{user.username}}!</h1>

    <br>

    <h3>Your one-stop shop for smart travel!</h3>

    <br>

    <h3>What would you like to do?</h3>
    {% else %}

    <div class = "main">
        <h1>Welcome to, Travel AI! New Here?</h1>
    
  
      
        <p> Ready to journey with us? </p> 
    
        <br>
    
        <a href="/register">Join Now!</a>
    </div>
    
    
    {% endif %}
  
</div>

  




{% endblock %}

blog/myapp/templates/base/master.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {# Import a custom font from google apis, called in master.css #}
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

  {# Syntax to reference the css file #}
  <link rel= "stylesheet" href= "{% static 'global.css' %}">
  {# Syntax to reference the css file #}

  {# Import Bootstrap 5 #}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  
  {# Name of Tab #}
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
    <div class = "container-fluid">
      <div>
        <ul class = "navbar-nav">
          
          <li class = "nav-item">
            <a class = "nav-link" href = "/"> Home </a> 
          </li>
          
          |
          
          <li class = "nav-item">
            <a class = "nav-link" href = "/feedback"> Discussion Thread</a>
          </li> 
          
          {% if user.is_authenticated%}  
          |
          <li class = "nav-item">
            <a class = "nav-link" href = "/create-feedback">Create Post</a>
          </li>
          {% else %}

          {% endif %}



          
          <!-- <li class = "nav-item">
            <a class = "nav-link" href = "/users_db"> USERS</a>
          </li> -->

        </ul>
      </div>

      <div>

        <ul class = "navbar-nav">
          
          {% if user.is_authenticated%}  

          <span class ="navbar-text"> Logged in as {{user.username}} | </span>

          <li class = "nav-item">
            <a class = "nav-link" href = "/log_out"> Logout</a>
          </li>

          {% else %}

          <li class = "nav-item">
            <a class = "nav-link" href = "/login">
            Login
            </a>
          </li>


          {% endif %}

          {# regardless of Logged in or not, show Register. After testing we can place this before endif for the final version #}
          <li class = "nav-item">
            <a class = "nav-link" href = "/register"> Register</a>
          </li>

        </ul>

        
     

      </div>

    </div>
  </nav>

  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
  </script>


{% block content %}{% endblock %}



{# since everything extends from master, best practice to place all recurring stuff here#}

</body>


<!-- <div class = "bottom_footer">
  <a href = ""> SUPPORT </a> | <a href = ""> HELP </a>
</div> -->

</html>

<!-- Because of the above code, all other html doesn't need the 
<!DOCTYPE html>... since it references this one -->